### ISSUE TITLE
Reforge price appears on items that can't be reforged

### ISSUE THREAD

**Issue by snowixdoom** [Zephilinox/ZephsImprovedTooltips#1]
I'm sure that you're aware of this issue but items like armor, pets, mounts, and grappling hooks will show their reforge price even though they can't be reforged.

**Comment by Zephilinox** [comment]
haha sorry for the late response. I can't remember if I released a new version years ago based on this or if I found some bugs myself, but hopefully 0.16.0 fixed the issues for you :)

feel free to reopen this if not
